---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
movie_data <- read_csv("tmdb_5000_movies.csv")
view(movie_data)
```

```{r}
glimpse(movie_data)
```

1. Could group by genre/status. Create a profit column that takes revenue away from budget. There's some NAs to deal with & some formatting issues with some character columns. 

2. 

```{r}
movies_selected <- movie_data %>% 
  select(title, runtime, budget)

movies_selected
```

3.

```{r}
movies_selected %>% 
 summarise(na_count_title = sum(is.na(title)),
           na_count_runtime = sum(is.na(runtime)),
           na_count_budget = sum(is.na(budget)))
```

4. 


```{r}
movies_runtime <- movies_selected %>% 
  mutate(runtime = na_if(runtime, "0"))

movies_runtime %>% 
  summarise(na_count_runtime = sum(is.na(runtime)))
```

5. 

```{r}
movies_imputed <- movies_runtime %>% 
  mutate(runtime = coalesce(runtime, median(runtime, na.rm = TRUE)))

movies_imputed %>% 
  filter(is.na(runtime))
```

6. 

```{r}
movies_imputed %>% 
  slice_min(runtime, n = 10)
```
```{r}
movies_imputed %>% 
  slice_max(runtime, n = 10)
```

7. 

```{r}
movies_imputed %>% 
  mutate(
    budget = if_else(budget < 100, median(budget), budget))
```

Extension
1. 

```{r}
movies_imputed %>% 
  mutate(budget_type = case_when(
    budget < 12e6 ~ "Small budget",
    budget >= 12e6 & < 40e6 ~ "Medium budget", 
    budget >= 40e6 ~ "Big budget"
  ))
```

